// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Kpo4310_asadovrs.Main
{
	public partial class MainWindow : NSWindowController
	{
		public MainWindow (IntPtr handle) : base (handle)
		{
		}
	}
}
