// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using Kpo4310_asadovrs.Lib;

namespace Kpo4310_asadovrs.Main
{
	public partial class SearchFormViewController : NSViewController
	{
        private Substance _substance;
        public Substance substance {
            get {
                return _substance;
            }
        }

        public SearchFormViewController (IntPtr handle) : base (handle)
		{
            _substance = null;
		}

        public void SetSubstance(Substance sub){
            _substance = sub;
            fillTextFields(sub);

        }
        [Export("buttonClick:")]
        public void buttonClick(Foundation.NSObject sender)
        {
            MockSubstanceListCommand loader = new MockSubstanceListCommand();
            loader.Execute();
            var result = loader.SearchSubstance(searchName.StringValue);
            fillTextFields(result);
        }

        private void fillTextFields(Substance substance){
            TFName.Enabled = true;
            TFName.StringValue = substance.name;

            TFType.Enabled = true;
            TFType.StringValue = substance.type.ToString();

            TFMinTemp.Enabled = true;
            TFMinTemp.StringValue = substance.lowTemperature.ToString();

            TFMaxTemp.Enabled = true;
            TFMaxTemp.StringValue = substance.highTemperature.ToString();
        }
	}
}
